// <auto-generated />
namespace EcoHostelAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedeventsclassesrulesandvolunteertimes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedeventsclassesrulesandvolunteertimes));
        
        string IMigrationMetadata.Id
        {
            get { return "201702062020558_added events, classes, rules, and volunteer times"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
